:PROPERTIES:
:ID:       2978669e-0fe6-463f-ba19-dfb410ff5cee
:END:
#+title: Logika - powt贸rka do kolosa
#+name: Logika_powtorka_do_kolosa
* Podstawy logiki 1
** Kluczowe tautologie KRZ
| nazwa                          | formua                         |
|--------------------------------+---------------------------------|
| prawo wyczonego rodka       | p \lor \not p                        |
| prawo sprzecznoci             | \not(p \land \not p)                     |
| prawo pdw贸jnej negacji         | \not\not p \leftrightarrow p                        |
| prawo transpozycji             | (p \rightarrow q) \leftrightarrow (\not q \rightarrow \not p)           |
| prawo sylogizmu warunkowego    |                                 |
|                                | ( p \rightarrow q) \land ( q \rightarrow r) \rightarrow ( p \rightarrow r) |
|                                | ( \rightarrow ) \rightarrow [( \rightarrow ) \rightarrow ( \rightarrow )]    |
|                                | ( \rightarrow ) \rightarrow [( \rightarrow ) \rightarrow ( \rightarrow )]    |
| prawo eksportacji i importacji | [(p \land q) \rightarrow r] \leftrightarrow [p \rightarrow (q \rightarrow r)]  |
|                                |                                 |

** Podstawy zda i formu KRZ
- zdanie w sensie logicznym :: zdanie oznajmujce, kt贸re przyjmuje warto 1 (PRAWDA) lub 0 (FASZ).
- sp贸jniki logiczne :: wyra偶enia su偶ce do budowy zda zo偶onych ze zda prostych. Podstawowe sp贸jniki logiczne to:
  + negacja, \not ; p \equiv \not\not p
  + koniunkcja, \land ; p \land q
  + alternatywa, \lor ; p \lor q
  + implikacja, \rightarrow ; p \rightarrow q
  + r贸wnowa偶no, \leftrightarrow ; p \leftrightarrow q



- Wasno ekstensjonalnoci :: Warto logiczna zdania zo偶onego zbudowanego za pomoc sp贸jnika logicznego zalezy wycznie od rodzaju tego sp贸jnika i wartoci logicznych skadowych zda prostych.

  Poprawnie zbudowane schematy zda nazywamy formuami Klasycznego Rachunku Zda.

  Zdanie zo偶one ze zda, kt贸re s formuami KRZ jest formu KRZ.

- Sia wizania sp贸jnik贸w
  \not \gt \land \lor \gt \rightarrow \leftrightarrow

- Wartociowanie zbioru zmiennych zdaniowych V ::
  + funkcja w:V \rightarrow {0, 1}
  + wartociowanie to przypisanie wartoci logicznych pewnym zmiennym zdaniowym, np:
    A = p \land q
    w(A) = 1 \equiv w(p \land q)
** Wyznacznie wartoci logicznej zdania zo偶onego

- We藕my zdanie A = "Je偶eli nieprawda, 偶e 5 > 4, to je偶eli 5 < 4, to 2 < 1 lub 2 < 3"

  1. Najpierw nale偶y utworzyc schemat logiczny A
     p : 5 \lt 4
     q : 2 \lt 1
     r : 2 \lt 3
     \not p \rightarrow (p \rightarrow q \lor r)
     
  2. Nastpnie ustalic wartoci logiczne zda prostych
     p = 0, q = 0, r = 1

  3. Podstawi te wartoci za zmienne p q r i przeprowadzi obliczenia zgodnie z tablicami prawdziwociowymi.

     \not 0 \rightarrow (0 \rightarrow 0 \lor 1)
     = 1 \rightarrow (0 \rightarrow 1)
     = 1 \rightarrow 1
     = 1

** Tablica prawdziwociowa formuy

Niech {p_1, p_2, ..., p_n} bdzie zbiorem zmiennych zdaniowych wystpujcych w formule A.

Istnieje 2^n wartociowa tego zbioru. By wyznaczy warto A dla ka偶dego z wartociowa nalezy utworzyc tabel prawdziwociow formuy A.

A = p \lor \not q \rightarrow \not p \land r
V = {p, q, r} - zbi贸r zmiennych zdaniowych w A

| p | q | r | \not p | \not q | p \lor \not q | \not p \land r | A |
|---+---+---+-----+-----+----------+----------+---|
| 1 | 1 | 1 |   0 |   0 |        1 |        0 | 0 |
| 1 | 1 | 0 |   0 |   0 |        1 |        0 | 0 |
| 1 | 0 | 1 |   0 |   1 |        1 |        0 | 0 |
| 1 | 0 | 0 |   0 |   1 |        1 |        0 | 0 |
| 0 | 1 | 1 |   1 |   0 |        0 |        1 | 1 |
| 0 | 1 | 0 |   1 |   0 |        0 |        0 | 1 |
| 0 | 0 | 1 |   1 |   1 |        1 |        1 | 1 |
| 0 | 0 | 0 |   1 |   1 |        1 |        0 | 0 |



- tautologia :: tautologi KRZ nazywamy formu KRZ, kt贸ra przyjmuje warto logiczn 1 dla ka偶dego warociowania.

- kontrtautologia :: kontrtautologi KRZ nazywamy formu KRZ, kt贸ra przymuje warto 0 dla ka偶dego wartociowania


#+begin_box
Je偶eli A jest tautologi KRZ, a formua A' powstaje z A przez podstawienie za wszystkie wystpienia pewnej zmioennej zdaniowej dowolnej formuy, to formua A' jest tautologi
#+end_box


- Przykad 1.
  A = "Olsztyn le偶y nad yn lub nieprawda, 偶e Olsztyn le偶y nad yn."

  1. Schemat logiczny A
     p \lor \not p

  2. Wartociowania - A zawiera 1 zmienn zdaniow, wic liczba wartociowa to 2^1
     p = 0, p \lor \not p = 0 \lor \not 0 = 0 \lor 1 = 1
     p = 1, p \lor \not p = 1 \lor \not 1 = 1 \lor 0 = 1

  3. A jest 1 dla wszystkich wartociowa, wic A jest tautologi


- Przykad 2.
  A = p \rightarrow (p \lor q)

  + Dow贸d wprost
    V = {p, q} - liczba wartosciowa to 2^2 = 4

    | p | q | p \lor q | p \rightarrow p \lor q |
    |---+---+--------+------------|
    | 1 | 1 |      1 |          1 |
    | 1 | 0 |      1 |          1 |
    | 0 | 1 |      1 |          1 |
    | 0 | 0 |      0 |          1 |

    Dla ka偶dego wartociowania zmiennych p i q fomrua jest prawdziwa, zatem jest tautologi.

  + Dow贸d nie wprost

    1. Zakadamy, 偶e A nie jest tautologi. Istnieje wtedy wartociowanie, dla kt贸rego A = 0.

       A ma form B \rightarrow C. Implikacja jest faszywa tylko gdy B = 1 i C = 0. Ten warunek zachodzi tylko gdy:

       a. p = 1 i p \lor q = 0

       b. p \lor q jest faszywe tylko wtedy gdy p = 0 i q = 0. Poniewa偶 p = 1 (a) i p = 0 (b) s sprzeczne, nie istnieje wartociowanie, dla kt贸rego A = 0. Zatem A jest tautologi.

* Podstawy logiki 2

- Wynikanie logiczne :: m贸wimy, 偶e formua A wynika logicznie z formu A_1, A_2, ..., A_n w KRZ, je偶eli dla ka偶dego wartociownia takiego 偶e w(A_1) = ... = w(A_n) = 1 r贸wnie偶 w(A) = 1.
  {A_1, ..., A_n} |= A

  Formua A wynika logicznie z formu A_1, ..., A_n iff A_1 \land ... \land A_n \rightarrow A jest tautologi KRZ.

  Poniewa偶 p \rightarrow q jest faszywe tylko dla p = 1, q = 0, A wynika z A_1, ..., A_n je偶eli A \neq 0


- Wnioskowanie :: ukad zda, z kt贸rych jedno jest wyr贸偶nione jako wniosek, a pozostae s przesankami. W KRZ schematy wnioskowa zapisujemy w postaci:

  \( \frac{A_1, ..., A_n}{A} \)

- Niezawodny schemat wniskowania :: taki schemat wnioskowania, w kt贸rym wniosek wynika logicznie z przeslanek w KRZ.


- Wnioskowanie dedukcyjne :: wnioskowanie kt贸rego schemat jest niezawodny.

- R贸wnowa偶no logiczna :: formua A jest r贸wnowa偶na logicznie formule B w KRZ, je偶eli W(A) = W(B) dla ka偶dego W.

  Formua A jest r贸wnowa偶na formule B w KRZ iff formua A \leftrightarrow B jest tautologi KRZ.

  R贸wno (a \leftrightarrow b) jest tautologi je偶eli a = b (dla ka偶dego wartociownia).

  Je偶eli formuy A i B s r贸wnowa偶ne w KRZ, a formua C' powstaje z C przez zastapienie niekt贸rych wystapie A przez B, to formuy C i C' s r贸wnowa偶ne.

- TODO: Dodatkowe funktory logiczne


- Definiowalno sp贸jnika logicznego :: sp贸jnik jednoargumentowy s jest definiowalny przez formu A(p) gdy formua s p jest r贸wnowa偶na logicznie formule A(p). M贸wimy, 偶e sp贸jnik dwuargumentowy s jest definiowalny przez formu A(p, q) gdy formua p `s` q jest r贸wnowazna formule A(p, q).
  

* Podstawy logiki 3


** Postacie normalne formu KRZ
- literay :: formuy p i \not p, gdzie p jest dowoln zmienn zdaniow.

- alternatywa elementarna :: alternatywa skoczenie wielu litera贸w.

- koniunkcja elementarna :: koniunkcja skoczenie wielu litera贸w.

- formua w koniunkcyjnej postaci normalnej (kpn) :: koniunkcja skoczenie wielu alternatyw elementarnych.

- formua w alternatywnej postaci normalnej (apn) :: alternatywa skoczenie wielu koniunkcji elementarnych.

#+begin_box
Ka偶da formua KRZ jest logicznie r贸wnowa偶na pewnej formule w kpn i pewnej formule apn
#+end_box


#+begin_box
Formua w kpn jest tautologi KRZ iff w ka偶dej skadowej alternatywie elementarnej wystpuje para przeciwnych litera贸w.
#+end_box

#+begin_box
Formua w apn jest kontrtautologi iff w ka偶dej skadowje koniunkcji elementarnej wystepuje para przeciwnych litera贸w.
#+end_box


** Sprowadzanie formu KRZ do apn i kpn metod przeksztace r贸wnowa偶nych

Podformuy danej formuy zastpujemy formuami r贸wnowa偶nymi w nastpujcej kolejnoci:

1. Eliminujemy sp贸jniki \leftrightarrow i \rightarrow zastpujc odpowiednio:
   + c \leftrightarrow d przez (c \rightarrow d) \land (d \rightarrow c)
   + c \rightarrow d przez (\not c \lor d)

2. Wprowadzamy znak negacji do wnetrza oraz usuwamy podw贸jn negacj zastpujc odpowiednio:
   + \not(c1 \land ... \land ck) przez (\not c1 \lor ... \lor \not ck)
   + \not(c1 \lor ... \lor ck) przez (\not c1 \land ... \land \not ck)
   + \not\not c przez c

3. Stosujemy:
   + Rozdzielczo koniunkcji wzgldem alternatywy (kpn):
     - d \lor (c1 \land ... \land ck) przez (d \lor c1) \land ... \land (d \lor ck)
     - (c1 \land ... \land ck) \lor d przez (c1 \lor d) \land ... \land (ck \lor d)
   + Rozdzielczo alternatywy wzgldem koniunkcji (apn):
     - d \land (c1 \lor ... \lor ck) przez (d \land c1) \lor ... \lor (d \land ck)
     - (c1 \lor ... \lor ck) \land d przez (c1 \land d) \lor ... \lor (ck \land d)

       
     
    
** Sprowadzanie formu KRZ do apn i kpn metod tablicow

A = p \land q \leftrightarrow q \land \not r

| p | q | r | p \land q | \not r | q \land \not r | A | apn | kpn |
|---+---+---+--------+-----+----------+---+-----+-----|
| 1 | 1 | 1 |      1 |   0 |        0 | 0 |     |     |
| 1 | 1 | 0 |        |     |          |   |     |     |
| 1 | 0 | 1 |        |     |          |   |     |     |
| 1 | 0 | 0 |        |     |          |   |     |     |
| 0 | 1 | 1 |        |     |          |   |     |     |
| 0 | 1 | 0 |        |     |          |   |     |     |
| 0 | 0 | 1 |        |     |          |   |     |     |
| 0 | 0 | 0 |        |     |          |   |     |     |


** Reguy tworzenia drzewa dowodowego




